name: CI

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]
  pull_request_target:
    branches: [master]

jobs:
  deploy:
    name: Build and publish images in ghcr
    runs-on: ubuntu-latest
    # Run only on pushing a tag
    strategy:
      matrix:
        image:
          - "pyspark-jupyter"
          - "pyspark"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get image tags
        run: |
          export IMAGE_TAGS="latest"
      - name: Populate image release tags
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export IMAGE_TAGS="pipelines,${GITHUB_REF#refs/tags/},$IMAGE_TAGS"

      - name: Build Docker Image
        run: |
          docker build -t ${{ matrix.image}} -f docker/${{ matrix.image }}.Dockerfile docker

      - name: Push Docker Image
        run: |
          for tag in $(echo $IMAGE_TAGS | tr "," " "); do
            dst_tag=ghcr.io/neuro-inc/${{ matrix.image }}:$tag
            docker tag ${{ matrix.image }} $dst_tag
            docker push $dst_tag
          done
